![imagen](./img/ejercicios.png)

# INFORMACIÓN DEL PROYECTO

### TÍTULO

Accidentes de trafico

### TEMA

Analizar los factores que influyen en la severidad de los accidentes de trafico

### HIPÓTESIS

Define aquí lo que será la hipótesis de tu proyecto.
Deberás tener más de una, pero tu proyecto lo harás teniendo una principal hipótesis.

- La principal contribucion a los accidentes fatales es el exceso de velocidad y las intersecciones

- La hora del dia influye significativamente a la frecuencia de los accidentes
- Hay picos de accidentes en ciertos meses

Casi seguro que se me ocurren mas mientras hago el EDA

## OBTENCIÓN DE LOS DATOS

### DATASETS Y FUENTES ALTERNATIVAS DE DATOS

Incluye aquí una vista del dataset o datasets de los que partirás para poder evaluar tu hipótesis. <br>
También incluye el origen de estos datos y su fuente.

In [1]:
import pandas as pd
# guarda en variables los datasets y su fuente
df_1 = pd.read_csv("./accidents.csv")
fuente_1 = "Kaggle"

Muestra mediante un head() los principales datasets con los que vas a trabajar

In [9]:
# Primer dataset
df_1.head()

,crash_date,traffic_control_device,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,roadway_surface_cond,road_defect,crash_type,...,most_severe_injury,injuries_total,injuries_fatal,injuries_incapacitating,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,crash_hour,crash_day_of_week,crash_month
0,07/29/2023 01:00:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,3.0,13,7,7
1,08/13/2023 12:11:00 AM,TRAFFIC SIGNAL,CLEAR,"DARKNESS, LIGHTED ROAD",TURNING,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0,1,8
2,12/09/2021 10:30:00 AM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,T-INTERSECTION,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,3.0,10,5,12
3,08/09/2023 07:55:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,ANGLE,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,NONINCAPACITATING INJURY,5.0,0.0,0.0,5.0,0.0,0.0,19,4,8
4,08/19/2023 02:55:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,T-INTERSECTION,STRAIGHT AND LEVEL,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,3.0,14,7,8

In [33]:
#%pip install lxml
a = pd.read_csv("ucrania-2025.csv", sep=";")
a.head()

,№,Region,Road Index,Road Name,Section Start (km+m),Section End (km+m),"GPS Coordinates, Start (Latitude/Longitude)","GPS Coordinates, End (Latitude/Longitude)",Accident Rate Coefficient,Hazard Level,Number of Road Accidents in the Three Years Prior to Registration
0,1,Вінницька,М-30,Стрий - Умань - Дніпро - Ізварине (через мм. В...,351+200,351+600,49.339347 28.063269,49.336843 28.067053,"0,5",Малонебезпечні,8.0
1,2,Вінницька,М-30,Стрий - Умань - Дніпро - Ізварине (через мм. В...,367+560,367+761,49.279056 28.256072,49.279571 28.258492,"0,36",NaN,5.0
2,3,Вінницька,М-30,Стрий - Умань - Дніпро - Ізварине (через мм. В...,406+904,407+300,49.192665 28.634312,49.190407 28.638263,"0,44",Малонебезпечні,6.0
3,4,Вінницька,М-30,Стрий - Умань - Дніпро - Ізварине (через мм. В...,490+918,490+918,48.80938066 29.40591751,48.80938066 29.40591751,"0,31",NaN,4.0
4,5,Вінницька,М-21,Виступовичі - Житомир - Могилів-Подільський (ч...,284+273,284+400,"49.40688022, 28.52797257","49.40586915, 28.52769145","0,42",Малонебезпечні,6.0

In [29]:
a.isna().sum() / len(a) * 100

DATAFLOW         0.000000
LAST UPDATE      0.000000
freq             0.000000
unit             0.000000
severity         0.000000
age              0.000000
nace_r1          0.000000
geo              0.000000
TIME_PERIOD      0.000000
OBS_VALUE        0.797267
OBS_FLAG        93.849658
CONF_STATUS    100.000000
dtype: float64

In [27]:
a["severity"].unique()

<ArrowStringArray>
['FAT']
Length: 1, dtype: str